### PR TITLE
Add removeArtifacts

### LINKED ISSUE #108: Allow all artifacts to be removed before updating release
**Is your feature request related to a problem? Please describe.**
I want to be able to have 1 release for github actions where my artifacts have a different filename each time the action is run.
Right now it just keeps adding artifacts to the same release, see https://github.com/Rosalie241/GLideN64/releases/tag/github-actions

**Describe the solution you'd like**
An option which'd remove *all* artifacts from the release before uploading the artifacts would be perfect.
I'm not really familiar with typescript/javascript (hence why I didn't open a PR) but I think something like this code should work?
```typescript
private async deleteArtifactsFromRelease(releaseId: number): Promise<void> {
    const releaseAssets = await this.releases.listArtifactsForRelease(releaseId)
    for (const artifact of releaseAssets) {
        core.debug(`Deleting existing artifact ${artifact.name}...`)
        await this.releases.deleteArtifact(artifact.id)
    }
}
```

**Describe alternatives you've considered**
I've considered keeping the filename the same but that isn't ideal.

**Additional context**
https://github.com/Rosalie241/GLideN64/blob/master/.github/workflows/build.yml#L198-L230
https://github.com/Rosalie241/GLideN64/releases/tag/github-actions

### PR DESCRIPTION
**Pull request by Rosalie241**
it seems like this works fine though I'm still not experienced with typescript/javascript so feedback is welcome.

Closes #108

### CODE REVIEW

**Comment by ncipollo** [comment]
Hey @Rosalie241,
Thanks for the PR!! I'll take a closer look when I get a chance later this week, but in the meantime, would you be able to also update tests (`Inputs.test.ts and `ArtifactUploader.test.ts`)?

**Comment by Rosalie241** [comment]
> Hey @Rosalie241,
> Thanks for the PR!! I'll take a closer look when I get a chance later this week, but in the meantime, would you be able to also update tests (`Inputs.test.ts and `ArtifactUploader.test.ts`)?

Done, tests should pass now, though I wasn't sure how to exactly add/test `removeArtifacts` in `ArtifactUploader.test.ts` so I left that alone for now.

**Review by ncipollo — CHANGES_REQUESTED** [review]
The changes look good, we just need to update the `ArtifactUploader` test now. Here are the steps I'd take to update that test:

1. Add a new argument to the test method which creates the artifact upload - `removes`.  This method can be found here https://github.com/ncipollo/release-action/blob/ec90733eaa25858c4558656bb4f87f2638ffe18f/__tests__/ArtifactUploader.test.ts#L173
2. Pass this new argument into the constructor for ArtifactUploader in the test.
3. Copy the `replaces all artifacts` test. Name the new test `removes all artifacts`. That test can be found here: https://github.com/ncipollo/release-action/blob/ec90733eaa25858c4558656bb4f87f2638ffe18f/__tests__/ArtifactUploader.test.ts#L73
4. Update the new test so it sets your flag instead of the `replaces` flag. I think you can leave the body of the test mostly the same. This will just verify that the uploader will delete all of the existing artifacts.

**Comment by Rosalie241** [comment]
added & pushed

**Review by ncipollo — APPROVED** [review]
Looks good! Thanks for the PR!! I'll do some additional testing next week then cut a new release with these changes in it.

**Pull request merged**
